autorizar/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.autenticar, name="autenticar"),
    # path('solicitar/<int:usuario_id>', views.solicitarRol, name="solicitar_rol"),
    path('activar/<int:usuario_id>', views.generarRol, name="activar"),
    # path('registro', views.registrar, name="registrar"),
    # path('cambioClave', views.passwordChange, name="passwordChange"),
] 

login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.autenticar, name="autenticar"),
    path('desactivado', views.desactivado, name="no_activo"),
    path('logout', views.desautenticar, name="logout"),
    path('registro', views.RegistrarWizardView.as_view(), name="registrar"),
    path('cambioClave', views.passwordChange, name="passwordChange"),
    path('completado', views.completado, name="completado"),
    path('recuperar_contraseña/', views.recuperar_contraseña, name='recuperar_contraseña'),
] 

autorizar/models.py
from django.db import models

# Create your models here.

autorizar/forms.py
from django import forms

class FormularioAutorizacion(forms.Form):
    opciones = [('autorizar', 'Autorizar'), ('rechazar', 'Rechazar')]
    seleccion = forms.ChoiceField(widget=forms.RadioSelect, choices=opciones, required=True)

login/forms.py
import re
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
        
class FormularioRegistrar(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput(), help_text=password_validation.password_validators_help_text_html(password_validation.get_default_password_validators()))
    confirm_password = forms.CharField(widget=forms.PasswordInput(), label="Confirmar contraseña")
    email = forms.EmailField(max_length=105)
    first_name = forms.CharField(max_length=70)
    last_name = forms.CharField(max_length=70)

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise ValidationError('Username is already in use.')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError('Email is already in use.')
        return email

    def clean_confirm_password(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise ValidationError("Passwords don't match.")
        return confirm_password
    
    def clean(self):
        cleaned_data = super().clean()

        password = cleaned_data['password']

        # Validate password using Django's password validators
        try:
            password_validation.validate_password(password, None)
        except ValidationError as e:
            self.add_error('password', e.messages[0])

        # Validate password using custom validators
        errors = {}
        if not re.search(r'[0-9]', password):
            errors['password'] = _('La contraseña debe contener almenos un número.')

        if not re.search(r'[a-zA-Z]', password):
            errors['password'] = _('La contraseña debe contener almenos una letra.')

        if not re.search(r'[~!@#$%^&*()_+-=\/\[\]{}|;:,<.>?"]', password):
            errors['password'] = [_('La contraseña debe contener almenos un caracter especial.')]

        if errors:
            for field, error in errors.items():
                self.add_error(field, error)

        return cleaned_data

class FormularioRol(forms.Form):
    rol = forms.ChoiceField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente')], widget=forms.HiddenInput)

class FormularioLogin(forms.Form):
    username= forms.CharField()
    password= forms.CharField(widget=forms.PasswordInput()) 

class CambiarPassword(forms.Form):
    oldPassword = forms.CharField(widget=forms.PasswordInput())
    password = forms.CharField(widget=forms.PasswordInput,
                               help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    def clean(self):
        if self.cleaned_data.get('password') != self.cleaned_data.get('password2'):
            raise forms.ValidationError('Passwords are not equal')
        password_validation.validate_password(self.cleaned_data.get('password'), None)
        return self.cleaned_data

autorizar/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from modelo.models import Usuario, Docente, Estudiante
from django.contrib import messages
from .forms import FormularioAutorizacion
from correo.views import emailRegistroCompletado

# #app autorizar 
# def solicitarRol (request, usuario_id):
#     user = request.user 
#     usuario = Usuario.objects.get(usuario_id=usuario_id)
#     if request.method == 'POST':
#         role = request.POST.get('role')            
#         if role == 'teacher':
#             usuario.autorizado = True
#             usuario.estado = False
#             usuario.save()
#         else:
#             return render(request, 'login/deactive.html')                                             #pagina de muestra de errores
#         return HttpResponseRedirect(reverse('autenticar'))
#     return render(request, 'autorizar/solicitarRol.html') 


@login_required
def generarRol (request,usuario_id):
    user = request.user
    if user.is_superuser:
        usuario = Usuario.objects.get(usuario_id=usuario_id)
        formulario_autorizacion = FormularioAutorizacion(request.POST)

        if request.method == 'POST':
            if formulario_autorizacion.is_valid():
                opcion_seleccionada = formulario_autorizacion.cleaned_data['seleccion']
                if opcion_seleccionada == 'autorizar':
                    user = User.objects.get(email = usuario.correo)
                    if usuario.autorizado:
                        
                        docente_model = Docente()
                        docente_model.usuario = usuario
                        usuario.autorizado = True                           # el usuario es considerado un docente
                        usuario.estado = True 
                        docente_grupo=Group.objects.get(name='docente')
                        user.groups.add(docente_grupo)
                        user.save()
                        usuario.save()
                        
                        docente_model.save()
                        print('docente Guardado')
                    else:
                        estudiante_model = Estudiante()                     # el usuario es considerado un estudiante
                        estudiante_model.usuario = usuario
                        usuario.estado = True 
                        usuario.save()
                        estudiante_grupo=Group.objects.get(name='estudiante')
                        user.groups.add(estudiante_grupo)
                        user.save()
                        estudiante_model.save()
                        print('estudainte Guardado')
                    nombre = usuario.nombres +" " + usuario.apellidos
                    url = request.build_absolute_uri(reverse('autenticar'))
                    messages.success(request, 'Usuario autorizado')
                    emailRegistroCompletado(usuario.correo,nombre, url)
                else:
                    usuario.delete()
                    print('usuario descartado')
                return HttpResponseRedirect(reverse('homepage'))
        return render(request, 'autorizar/autorizar.html',locals()) 
    return render(request, 'login/forbidden.html') 

templates/autorizar/autorizar.html
{% extends 'master.html' %}
{% block contenido %}
    <style>
        /* Estilos para el cuerpo */
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
            position: relative;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        /* Contenedor principal del formulario */
        .form-container {
            background-color: #fff;
            border-radius: 10px;
            padding: 20px;
            box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
            text-align: center;
            margin: 50px auto;
            max-width: 500px;
        }

        /* Estilos para los encabezados */
        h2 {
            font-size: 24px;
            margin-bottom: 10px;
            color: #333;
            
        }

        /* Estilos para la información del usuario */
        .user-info {
            font-size: 16px;
            margin-bottom: 20px;
            color: #555;
            text-align: left;
        }

        .user-info label {
            display: block;
            margin: 6px 0;
            font-weight: bold;
        }

        .user-info strong {
            font-weight: normal;
        }

        /* Estilos para la sección de selección */
        .selection-container {
            margin-bottom: 20px;
            
        }

        /* Estilos para el formulario y su grupo de opciones */
        .form-group {
            margin-bottom: 20px;
            
        }

        .form-label {
            display: block;
            margin-bottom: 6px;
            font-weight: bold;
            text-align: left;
            color: #000000;
        }
          .user-info label {
            display: block;
            margin: 6px 0;
            font-weight: bold;
            color: #000000;
        }

        /* Estilos para las opciones de radio */
        .radio-option {
            display: flex;
            align-items: center;
            justify-content: flex-start; /* Alineación horizontal */
            margin-bottom: 10px;
        }

        .radio-option label {
            margin-left: 10px;
            font-family: Arial, sans-serif; /* Aplica el mismo tipo de letra */
            color: #000000;
        }

        /* Estilos para el botón de selección */
        .radio-button {
            margin-right: 10px;
        }

        /* Estilos para el contenedor de botones */
        .button-container {
            display: flex;
            justify-content: center;
        }

        /* Estilos para el botón de enviar */
        .submit-button {
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            padding: 12px 24px;
            font-size: 14px;
            cursor: pointer;
            transition: background-color 0.3s;
            text-transform: uppercase;
        }

        .submit-button:hover {
            background-color: #0056b3;
        }
    </style>

    <div class="form-container">
        {% if usuario.autorizado %}
        <h2>Autorización para un docente</h2>
        <div class="user-info">
            <label>Nombre: <strong>{{usuario.nombres}}</strong></label>
            <label>Apellidos: <strong>{{usuario.apellidos}}</strong></label>
            <label>Correo: <strong>{{usuario.correo}}</strong></label>
        </div>
        {% else %}
        <h2>Autorización para un estudiante</h2>
        <div class="user-info">
            <label>Nombre: <strong>{{usuario.nombres}}</strong></label>
            <label>Apellidos: <strong>{{usuario.apellidos}}</strong></label>
            <label>Correo: <strong>{{usuario.correo}}</strong></label>
        </div>
        {% endif %}
        <div class="selection-container">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="form-label">Opción de autorización:</label>
                    <div class="radio-option">
                        <input type="radio" id="id_seleccion_0" name="seleccion" value="autorizar" required class="radio-button">
                        <label for="id_seleccion_0">Autorizar</label>
                    </div>
                    <div class="radio-option">
                        <input type="radio" id="id_seleccion_1" name="seleccion" value="rechazar" required class="radio-button">
                        <label for="id_seleccion_1">Rechazar</label>
                    </div>
                </div>
                
                <div class="button-container">
                    <button class="submit-button" type="submit">Enviar</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/autorizar/solicitarRol.html
{% extends 'master.html' %}

{% block contenido %}
{% load static %}
{% load i18n %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}

<head>
    <title>Seleccionar Rol</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/autorizar/seleccionar_rol.css' %} " media="screen">
    <link id="u-theme-google-font" rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
</head>
<style>
    .u-repeater-item {
        height: 340px; /* Ajusta la altura de los elementos */
        max-width: 340px;
        padding: 10px; /* Ajusta el espacio interno de los elementos */
        text-align: center; /* Centra el contenido en cada elemento */
        display: inline-block; /* Cambia el diseño a en línea */
        margin: -70px 100px 50px 50px; /* Margen superior, derecho, inferior, izquierdo */; 
    }
    .u-icon {
        font-size: 36px; /* Ajusta el tamaño de los iconos según tus preferencias */
        margin-bottom: 10px; /* Ajusta el espacio entre los iconos y el texto */
    }
</style>
    <p>Paso {{ wizard.steps.step1 }} de {{ wizard.steps.count }}</p>
    {% if wizard.form.forms %}
    <p>algo</p>
    {% else %}
    <section class="u-align-center u-clearfix u-custom-color- u-section-1" id="sec-7573">
        <div class="u-clearfix u-sheet u-sheet-1">
            <h7 class="u-text u-text-default u-text-1"style=" color: #000000; font-size: 30px; margin-top: 30px; font-family: Arial, sans-serif;">Escoja su Rol </h7>
            <form method="POST">
                {% csrf_token %}
                {{ wizard.management_form }}
                <div class="u-list u-list-1">
                    <div class="u-repeater u-repeater-1">
                        <div
                            class="u-align-center u-container-style u-custom-color- u-custom-item u-list-item u-repeater-item u-list-item-1">
                            <div class="u-container-layout u-similar-container u-container-layout-1">
                                <span class="u-icon u-text-white u-icon-1">
                                    <i class="fas fa-user-graduate"style="margin-top: -50px;color: #000000;"></i>
                                </span>
                                <h5 class="u-text u-text-default u-text-4" style="text-transform: capitalize; color: #000000; font-size: 19px; margin-top: -120px;">Estudiante</h5>
                                <p class="u-text u-text-3"style="font-size: 14px"> Capaz de realizar los análisis, y enviarlos a un docente
                                    para su
                                    revisión.</p>
                                <button type="submit" onclick="setRolValue('estudiante');"
                                    class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-4 u-radius-50 u-text-body-color u-btn-1"
                                    name="rol" value="estudiante"style="text-transform: capitalize">Seleccionar</button>
                            </div>
                        </div>
                        <div
                            class="u-align-center u-container-style u-custom-color- u-custom-item u-list-item u-repeater-item">
                            <div class="u-container-layout u-similar-container u-container-layout-2">
                                <span class="u-icon u-text-white u-icon-2">
                                    <i class="fas fa-chalkboard-teacher"style="margin-top: -50px;color: #000000;"></i>
                                </span>
                                <h5 class="u-text u-text-default u-text-4" style="text-transform: capitalize; font-weight: bold; color: #000000; font-size: 19px; margin-top: -130px;">Docente</h5>
                                <p class="u-text u-text-3"style="font-size: 14px"> Subir documentos, generar análisis y opciones avanzadas para
                                    realizar un
                                    análisis.</p>
                                <button type="submit" onclick="setRolValue('docente');"
                                    class="u-border-none u-btn u-btn-round u-button-style u-custom-color-2 u-hover-custom-color-4 u-radius-50 u-text-body-color u-btn-2"
                                    name="rol" value="docente"style="text-transform: capitalize">Seleccionar</button>
                            </div>
                        </div>
                    </div>
                </div>
                <input type="hidden" id="id_rol" name="{{ wizard.form.prefix }}-rol" value="{{ wizard.form.rol.value }}">
            </form>
        </div>
    </section>
    {% endif %}

<script>
    function setRolValue(value) {
        document.getElementById("id_rol").value = value;
    }
</script>
{% endblock %}